# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy the HTML file to the default Nginx public directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
